theme: minima

title: mmoumni
author: Mohamed Moumni
email: mmoumniwork@gmail.com
url: https://mmoumni.me/

timezone: Etc/UTC # GitHub uses UTC. This is to force dev environment to match

description: >
  

github_username:   Mohamed-Moumni
linkedin_username: mohamed-moumni-6922a41b9

rss: rss

show_excerpts: false

# Used by simple links page
social-links:
  Resume:        https://mmoumni.me/resume/
  LinkedIn:      https://linkedin.com/in/mohamed-moumni-6922a41b9/
  GitHub:        https://github.com/Mohamed-Moumni/
  Website:       https://mmoumni.me/

# plugin: jekyll-seo-tag
social:
  name: Mohamed Moumni
  links:
    - https://linkedin.com/in/mohamed-moumni-6922a41b9
    - https://github.com/Mohamed-Moumni

# plugin: jekyll-titles-from-headings
titles_from_headings:
  strip_title: true

collections:
  personal: # collection for personal blog posts
    output: true

header_pages:
  - resume.html
  # - books.md

plugins:
  - jekyll-feed
  - jekyll-sitemap

google_analytics:
  - UA-185058308-1 # Old GA Universal Analytics property
  - G-RY6FRPMXHZ # New GA4 property

gravatar_hash: 2136e716a089f4a3794f4007328c7bfb
code_block_max_height: 500px

home_post_limit: 5

defaults:
  - scope:
      path: ""
    values:
      image: https://avatars.githubusercontent.com/u/78799596?v=4 # Apply default site image
  - scope:
      path: ""
      type: posts
    values:
      tags:
        - Other # Add a default tag to all posts

# Disable highlighting to use highlightJS instead
# highlighter: none # Not supported by GitHub Pages
kramdown:
  syntax_highlighter_opts:
    disable: true
